name = "Lapce-Markdown"
version = "0.1.0"
author = "zarathir"
display-name = "Markdown"
description = "Lapce Markdown powered by Marksman"
wasm = "bin/lapce-markdown.wasm"

[activation]
language = []
workspace-contains = []

[config."lsp.serverPath"]
default = ""
description = "Path to custom LSP executable"

# [config."lsp.serverArgs"]
# default = []
# description = ""

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
