name = "Lapce-Markdown"
version = "0.2.2"
author = "zarathir"
display-name = "Markdown"
description = "Markdown powered by Marksman"
wasm = "bin/lapce-markdown.wasm"
icon = "markdown-logo.png"
repository = "https://github.com/zarathir/lapce-markdown"

[activation]
language = ["markdown"]
workspace-contains = []

[config."lsp.serverPath"]
default = ""
description = "Path to custom LSP executable"

# [config."lsp.serverArgs"]
# default = []
# description = ""

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
